In [6]:
from Coach import Coach
from connectfour.ConnectFourGame import ConnectFourGame as Game
from connectfour.keras.NNet import NNetWrapper as nn
from utils import *

In [7]:
args = dotdict({
    'numIters': 1,
    'numEps': 1,
    'tempThreshold': 15,
    'updateThreshold': 0.6,
    'maxlenOfQueue': 200000,
    'numMCTSSims': 25,
    'arenaCompare': 40,
    'cpuct': 1,

    'checkpoint': './temp/',
    'load_model': False,
    'load_folder_file': ('/dev/models/8x100x50','best.pth.tar'),
    'numItersForTrainExamplesHistory': 20,

})

if __name__=="__main__":
    g = Game()
    nnet = nn(g)

    if args.load_model:
        nnet.load_checkpoint(args.load_folder_file[0], args.load_folder_file[1])

    c = Coach(g, nnet, args)
    if args.load_model:
        print("Load trainExamples from file")
        c.loadTrainExamples()
    c.learn()

------ITER 1------
Self Play |################################| (1/1) Eps Time: 8.947s | Total: 0:00:08 | ETA: 0:00:00
Checkpoint Directory exists! 
input board
[[[ 0 -1  0 ...  0  1 -1]
  [ 0  0  0 ...  0  0  0]
  [ 0  1  0 ...  0  0  0]
  [ 1  0  0 ... -1  1  0]
  [ 0 -1 -1 ...  0  0  0]
  [ 0  0  0 ...  0  1  0]]

 [[ 0 -1  0 ...  0  1 -1]
  [ 0  0  0 ...  0  0  0]
  [ 0  1  0 ...  0  0  0]
  [ 1  0  0 ... -1  1 -1]
  [ 0 -1 -1 ...  1  0  0]
  [ 0  0  0 ...  0  1  0]]

 [[ 0  0  0 ...  0  1 -1]
  [ 0  0  0 ...  0  0  0]
  [ 0  1  0 ...  0  0  0]
  [ 0  0  0 ... -1  0  0]
  [ 0 -1  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 ...

 [[-1  1  0 ...  0 -1  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  1  0]
  [ 0  1 -1 ...  0  0  0]
  [ 0  0  0 ...  0 -1  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 0 -1  0 ...  0  0  0]
  [ 0  0 -1 ...  1  1  0]
  [ 0 -1  1 ...  0  0 -1]
  [ 0  0  0 ...  0 -1  0]
  [ 0  0  0 ...  0  0  0]
  [ 1 -1  0 ...  0  1  0]]

 [[ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  

In [3]:
import numpy as np

In [4]:
x= [[1,2,3],[4,5,6]]
x

[[1, 2, 3], [4, 5, 6]]

In [5]:
newB = np.rot90(x, 3)
newB

array([[4, 1],
       [5, 2],
       [6, 3]])