In [1]:
from Coach import Coach
from connectfour.ConnectFourGame import ConnectFourGame as Game
from connectfour.keras.NNet import NNetWrapper as nn
from utils import *

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
args = dotdict({
    'numIters': 1,
    'numEps': 2,
    'tempThreshold': 15,
    'updateThreshold': 0.6,
    'maxlenOfQueue': 200000,
    'numMCTSSims': 25,
    'arenaCompare': 40,
    'cpuct': 1,

    'checkpoint': './temp/',
    'load_model': False,
    'load_folder_file': ('/dev/models/8x100x50','best.pth.tar'),
    'numItersForTrainExamplesHistory': 20,

})

if __name__=="__main__":
    g = Game()
    nnet = nn(g)

    if args.load_model:
        nnet.load_checkpoint(args.load_folder_file[0], args.load_folder_file[1])

    c = Coach(g, nnet, args)
    if args.load_model:
        print("Load trainExamples from file")
        c.loadTrainExamples()
    c.learn()

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
------ITER 1------
Self Play |################################| (2/2) Eps Time: 9.570s | Total: 0:00:19 | ETA: 0:00:110
Checkpoint Directory exists! 
input board
[[[ 0  1  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0 -1]
  [ 1  0  0 ...  0  0 -1]
  [ 0  0  0 ...  0  0  0]
  [ 0  0 -1 ...  0  0  0]]

 [[ 0  0  0 ... -1 -1  0]
  [ 0  0 -1 ...  0 -1  1]
  [ 1  0  0 ...  0  0  1]
  [ 1  0  0 ...  0  0 -1]
  [-1  0  1 ...  0  0  0]
  [-1  1  1 ...  1 -1  0]]

 [[ 0  0  0 ...  1  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 1  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0 -1 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 ...

 [[ 0  0  0 ...  0  0  0]
  [ 0  1  1 ...  1  0  0]
  [ 0 -1  0 ...  0  1 -1]
  [-1  0  1 ...  0  0 -1]
  [-1  0  0 ...  0  0  0]
  [ 0  0 

In [3]:
import numpy as np

In [4]:
x= [[1,2,3],[4,5,6]]
x

[[1, 2, 3], [4, 5, 6]]

In [5]:
newB = np.rot90(x, 3)
newB

array([[4, 1],
       [5, 2],
       [6, 3]])